config/routes.rb
Rails.application.routes.draw do
  get "/", to: "pages#home", as: "root"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :listings, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :breed
  enum sex: { female: 0, male: 1 }
  validates :sex, presence: true
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:show, :edit, :update, :destroy]

    def index
        @listings = Listing.all
    end

    def show

    end

    def new
        set_breeds_and_sexes
        @listing = Listing.new
    end

    def create
        #finish logic for creating a record
        @listing = Listing.create(listing_params)
        if @listing.errors.any?
            set_breeds_and_sexes
            render "new"
        else 
            redirect_to listings_path
        end
    end

    def edit
        set_breeds_and_sexes
        @listing = Listing.new
    end

    def update
        #finsih logic for updating the record
    end

    def destroy
        
        #finish logic for deleting the record
    end

    private

    def set_listing
        @listing = Listing.find(params[:id])
    end

    def set_breeds_and_sexes
        @breeds = Breed.all
        @sexes = Listing.sexes.keys
    end

    def listing_params
        params.require(:listing).permit(:title, :description, :breed_id, :sex, :city, :state, :price, :deposit, :date_of_birth, :diet, :picture)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render plain: "home page"
    end

    def not_found
        render plain: "not found"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snakebay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<h1>New Listing</h1>

<% if @listing.errors.any? %>
    <% @listing.errors.full_messages.each do |message| %>
        <li style="color: red"><%= message %></li>
    <% end %>
<% end %>


<%= form_with(model: @listing, local: true) do |form| %>
    <div class="title-field">
        <%= form.label :title  %>
        <%= form.text_field :title, value: @listing.title %>
    </div>

    <div>
        <%= form.label :breed_id %>
        <%= form.select(:breed_id, @breeds.map{|b| [b.name, b.id]} ) %>
    </div>
    <% @sexes.each do |option| %>
        <%= form.radio_button :sex, option %>
        <%= form.label option %>
    <% end %>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0 %>
    </div>
    <div>
        <%= form.label :deposit %>
        <%= form.number_field :deposit, min: 0 %>
    </div>
    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>
    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/index.html.erb
<%  for listing in @listings %>
    <li>
        <%= link_to listing.title, listing_path(listing.id)%>
        <%= image_tag listing.picture if listing.picture.attached? %>
    </li>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<% if @listing.errors.any? %>
    <% @listing.errors.full_messages.each do |message| %>
        <li style="color: red"><%= message %></li>
    <% end %>
<% end %>


<%= form_with(model: @listing, local: true) do |form| %>
    <div class="title-field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :breed_id %>
        <%= form.select(:breed_id, @breeds.map{|b| [b.name, b.id]} ) %>
    </div>
    <% @sexes.each do |option| %>
        <%= form.radio_button :sex, option %>
        <%= form.label option %>
    <% end %>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0 %>
    </div>
    <div>
        <%= form.label :deposit %>
        <%= form.number_field :deposit, min: 0 %>
    </div>
    <div>
        <%= form.label :city %>
        <%= form.text_field :city %>
    </div>
    <div>
        <%= form.label :state %>
        <%= form.text_field :state %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet %>
    </div>


    <div>
        <%= form.label :picture %>
        <%= form.file_field  :picture, accept: "image/png,image/gif,image/jpeg,image/jpg"%>
        <% if @listing.errors.any? %>
            FILL THIS OUT AGAIN
        <% end %>
    </div>


    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/show.html.erb
show